const cartActionTypes = {
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
}

export default cartActionTypes;